### ISSUE TITLE
JoinRoomList 확인 요망

### ISSUE THREAD

**Issue by hanggyh7** [kishe89/BattleGroundChatBot#56]
방 생성 후 어떠한 작업도 하지 않고 재실행하면 방 list가 제대로 출력되지 않음.
확인필요.

**Comment by hanggyh7** [comment]
방을 나가면 item index가 적은 방들도 전부 나가짐.
room1, room2, room3, room4, room5가 있다고 가정할 때 room4를 나가면 room1~room3도 전부 나가지고 room5만 남음.
이거 우선 확인중임.

**Comment by kishe89** [comment]
해결되었으므로 닫습니다.
